--collegues
--insert into collegue (NOM,PRENOM, EMAIL) values ('Admin','DEV','admin@dev.fr');
--insert into collegue (NOM,PRENOM, EMAIL) values ('User','DEV','user@dev.fr');

--frais
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',15,'Hôtel', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',25,'Restaurant', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',10,'Peaje', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',21,'Restaurant', 2);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',22,'Hôtel', 2);



--Natures
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-01','2020-01-01',0,'Conseil',10,0,5,5,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-02','2020-02-01',0,'Formation',10,0,5,5,0);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Expertice Technique',10,1,5,5,0);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Pause Café',10,1,5,5,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Fête Anniversaire',10,0,5,5,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Fête Anniversaire',10,0,5,5,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Fête Anniversaire',10,0,5,5,1);

--Missions
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','INITIALE','couvaturage','Montpellier','Lille',1);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','EN_ATTENTE_VALIDATION','train','Montpellier','Barcelone',2);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','VALIDEE','voiture','Montpellier','Nimes',3);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','REJETEE','vélo','Montpellier','New York',2);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','INITIALE','vélo','Montpellier','Caracas',3);

--frais

insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',15,'Hôtel', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',25,'Restaurant', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',10,'Peaje', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',21,'Restaurant', 2);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',22,'Hôtel', 2);












