--collegues
--insert into collegue (NOM,PRENOM, EMAIL) values ('Admin','DEV','admin@dev.fr');
--insert into collegue (NOM,PRENOM, EMAIL) values ('User','DEV','user@dev.fr');

--Natures
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-01','2020-01-01',0,'Conseil',45,0,15,5,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-02','2020-02-01',0,'Formation',30,0,10,5,0);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Expertice Technique',18,1,5,5,0);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Pause Café',20,1,25,5,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Fête Anniversaire',15,0,50,8,1);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Fête Anniversaire',12,0,45,7,0);
insert into nature(DEBUT_VALIDITE, FIN_VALIDITE, MISSION_FACTUREE, NOM, PLAFOND, PLAFOND_DEPASSABLE, POURCENTAGE_PRIME, TJM, VERSEMENT_PRIME) values ('2020-01-03','2020-02-01',1,'Fête Anniversaire',11,0,55,6,1);



--Missions
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2019-01-01','2019-01-03','INITIALE','couvaturage','Montpellier','Lille',1);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2019-01-01','2019-01-03','INITIALE','train','Montpellier','Barcelone',2);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2018-01-01','2018-01-03','INITIALE','voiture','Montpellier','Nimes',3);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2018-01-01','2018-01-03','INITIALE','vélo','Montpellier','New York',2);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2018-01-01','2018-01-03','INITIALE','vélo','Montpellier','Caracas',3);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','INITIALE','couvaturage','Montpellier','Lille',1);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-12-12','INITIALE','train','Montpellier','Barcelone',2);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-10-15','INITIALE','voiture','Montpellier','Nimes',3);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-10-20','INITIALE','vélo','Montpellier','New York',2);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-10-31','INITIALE','vélo','Montpellier','Caracas',3);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','INITIALE','couvaturage','Montpellier','Lille',1);
insert into mission(DATE_DEBUT, DATE_FIN ,STATUT ,TRANSPORT ,VILLE_ARRIVEE ,VILLE_DEPART, NATURE_ID) values ('2020-01-01','2020-01-03','INITIALE','couvaturage','Montpellier','Lille',3);

--frais
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',15,'Hôtel', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',25,'Restaurant', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',10,'Peaje', 1);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',21,'Restaurant', 2);
insert into frais(DATE, MONTANT_FRAIS, NATURE_FRAIS, MISSION_ID) values ('2020-01-02',22,'Hôtel', 2);


















